name: Build the plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Package
        run: chmod +x ${{github.workspace}}/RetakesAllocator/release.sh; ${{github.workspace}}/RetakesAllocator/release.sh
      - name: Publish DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: RetakesAllocator-${{github.ref}}-${{github.sha}}
          path: RetakesAllocator.zip
