name: Build RetakesAllocator.zip

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build
        shell: bash
        run: dotnet build --no-restore -c Release
      - name: Package
        working-directory: ${{github.workspace}}/RetakesAllocator/
        run: chmod +x release.bash; ./release.bash
      - name: Publish Archive for Branch
        uses: actions/upload-artifact@v4
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: RetakesAllocator-${{github.sha}}
          path: ${{github.workspace}}/RetakesAllocator/bin/Release/RetakesAllocator
      - name: Publish Archive for Release
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: RetakesAllocator-${{github.ref_name}}
          path: ${{github.workspace}}/RetakesAllocator/bin/Release/RetakesAllocator
      - name: Attach Release Files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: RetakesAllocator-${{github.ref_name}}
